// <auto-generated />
namespace Cdf54.Ja.SignalR.Chat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Pseudo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pseudo));
        
        string IMigrationMetadata.Id
        {
            get { return "201504081313144_Pseudo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
